### ISSUE TITLE
Evaluation clarification

### ISSUE THREAD

**Issue by reyhanehjaafari** [shirin1996/Prediction_Project#5]
In the "Transformer.ipynb" after the "Run the model" part There is an evaluation method, But there is nothing to describe that does the evaluation works fine or not? 
Please compare specific results with each other and clarify how good or bad the evaluation is.
Please explain if the current metric is good or there should be other metrics for evaluation.

**Comment by shirinyamani** [comment]
Thank you very much for your suggestion. I have evaluated my model on my test dataset. The code has been updated!
@reyhanehjaafari
