### ISSUE TITLE
Explanation for loop

### ISSUE THREAD

**Issue by reyhanehjaafari** [shirin1996/Prediction_Project#7]
In the last part of the code in the"Transformer.ipynb" file, I did not understand why there is a for loop which just works once. If it has to be executed once please use a method. If it should be for loop please explain it in the comments of the code.

**Comment by shirinyamani** [comment]
It has been set to one because the number of training `epochs` is `1`. This is because I did not have access to GPU based engine, and if I set the number of epochs to a bigger number(>10), it would have take whole day to be trained, including time complexity! @reyhanehjaafari
